#!/usr/bin/env bash

source ${WORKING_DIR}/common/functions.sh

hook::config() {
  cat <<EOF
{
   "onKubernetesEvent": [
      {
         "kind": "secret",
         "event": [
            "add",
            "update"
         ],
         "selector": {
            "matchLabels": {
                "${SECRET_LABEL}": "yes"
            }
         },
         "namespaceSelector": {
            "matchNames": [
               "${SECRET_NAMESPACE}"
            ]
         }
      }
   ]
}
EOF
}

hook::trigger() {
  for secret in $(jq -r '.[] | .resourceName' $BINDING_CONTEXT_PATH)
  do
    for namespace in $(secret::get_destination_namespaces "secret/${secret}"); do
      secret::replicate "secret/${secret}" ${namespace}
    done
  done
}

common::run_hook "$@"
