#!/usr/bin/env bash

source ${WORKING_DIR}/common/functions.sh

hook::config() {
  cat <<EOF
{
   "onKubernetesEvent": [
      {
         "kind": "secret",
         "event": [
            "delete"
         ],
         "selector": {
            "matchLabels": {
                "${SECRET_LABEL}": "yes"
            }
         },
         "namespaceSelector": {
            "matchNames": [
               "${SECRET_NAMESPACE}"
            ]
         }
      }
   ]
}
EOF
}

hook::trigger() {

  for secret in $(jq -r '.[] | .resourceName' $BINDING_CONTEXT_PATH); do
    for namespace in $(kubectl get ns -o name); do
        if [[ "${namespace##*/}" != "${SECRET_NAMESPACE}" ]]; then
            if $(kubectl -n ${namespace##*/} get secret ${secret} &>/dev/null); then
                kubectl -n ${namespace##*/} delete secret ${secret} &>/dev/null
            fi
        fi
    done
  done

}

common::run_hook "$@"
